### ISSUE TITLE
Seem not work in IPv6 only

### ISSUE THREAD

**Issue by valentin2105** [rundeck-plugins/slack-incoming-webhook-plugin#20]
Hello,

I try to make this plugin work on IPv6,

My Mattermost server run on dual-stack but my Rundeck run on IPv6-only,

```
 ERROR services.NotificationService [quartzScheduler_Worker-2] - Error sending notification: Notification{eventTrigger='onfailure', type='SlackNotification', format='null', con
tent='{"webhook_base_url":"https://mattermost-server.tld/hooks","webhook_token":"MYTOKEN"}'}: class com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data t
o Slack URL: [Network is unreachable (connect failed)].                                                                                                                                                  com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [Network is unreachable (connect failed)].                                                                at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:223) ~[?:?]                                                                                 at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.invokeSlackAPIMethod(SlackNotificationPlugin.java:183) ~[?:?]
        at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.postNotification(SlackNotificationPlugin.java:127) ~[?:?]                                                                                 at com.dtolabs.rundeck.plugins.notification.NotificationPlugin$postNotification.call(Unknown Source) ~[?:?]                                                                                              at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:762) ~[classes!/:?]                                                                                                     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]                                                                                                          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]                                                                                                  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]                                                                                                                                       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]                                                                                                                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[groovy-2.5.6.jar!/:2.5.6]                                                                            at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) ~[groovy-2.5.6.jar!/:2.5.6]                                                                             at rundeck.services.NotificationService$_triggerJobNotification_closure12.doCall(NotificationService.groovy:549) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]                                                                                                                            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]                                                                                                          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]                                                                                                  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]                                                                                                  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]                                                                                                                 at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
```
My rundeck server run with `-Djava.net.preferIPv6Addresses=true` but this seem to do nothing with the plugin. 

Thanks !

**Comment by fdevans** [comment]
Sorry we missed this.  If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
